[project]
name = "stageD"
version = "0.2.0"
description = "Staging Daemon for ASF Websites"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "asfpy>=0.56",
]

[dependency-groups]
dev = [
    "ruff>=0.14.4",
]
